### ISSUE TITLE
Use hyperlinks instead of Table numbers

### ISSUE THREAD

**Issue by jcohenadad** [Diffusion-MRI/awesome-preclinical-diffusion-mri#2]
From the README: "(Table 1 and Table 2), a list of available software dedicated to image acquisition (Table 3), a list of software available for data pre-processing (Table 4), and a list of software available for model fitting (Table 5).", however, the tables are not numbered. I suggest to instead use hyperlinks.

**Comment by schillkg** [comment]
Hyperlinks have now been added instead of table numbers
