### ISSUE TITLE
Repetead link

### ISSUE THREAD

**Issue by RicardoRios46** [Diffusion-MRI/awesome-preclinical-diffusion-mri#3]
In the [Data aquisition](https://github.com/Diffusion-MRI/awesome-preclinical-diffusion-mri#data-acquisition) section  the double PFG URL have the same URL name of the remmi sequence (but the URL works).

Saludos!,

Ricardo Rios

PD: Thanks for the awesome list!

**Comment by Diffusion-MRI** [comment]
Thank you - Fixed! We hope this will be useful resource for those looking for datasets or acquisition/processing tools. If there are any that you frequently use and advocate for feel free to make suggestions!
