### ISSUE TITLE
to be added to data resource

### ISSUE THREAD

**Issue by schillkg** [Diffusion-MRI/awesome-preclinical-diffusion-mri#4]
Human brain data: [https://elifesciences.org/articles/73153](https://www.google.com/url?q=https://elifesciences.org/articles/73153&sa=D&source=docs&ust=1673970408430917&usg=AOvVaw0Os9AY-wVpbjq5C6uUnzud) - data available at [https://open.win.ox.ac.uk/DigitalBrainBank/#/](https://www.google.com/url?q=https://open.win.ox.ac.uk/DigitalBrainBank/%23/&sa=D&source=docs&ust=1673970408431090&usg=AOvVaw0RyRX-tHxUbzBERNhHDxX7)

**Comment by schillkg** [comment]
Maccaque resource: [https://www.biorxiv.org/content/10.1101/2022.09.08.506363v1](https://www.google.com/url?q=https://www.biorxiv.org/content/10.1101/2022.09.08.506363v1&sa=D&source=docs&ust=1673986331375784&usg=AOvVaw1n-5cgsM6N0TY4nvny05-6) - data available on [https://open.win.ox.ac.uk/DigitalBrainBank/#/](https://www.google.com/url?q=https://open.win.ox.ac.uk/DigitalBrainBank/%23/&sa=D&source=docs&ust=1673986331375901&usg=AOvVaw2Lcm0MaDeJEFfu4VEd91h5)

**Comment by schillkg** [comment]
[https://www.biorxiv.org/content/10.1101/2022.09.08.506363v1](https://www.google.com/url?q=https://www.biorxiv.org/content/10.1101/2022.09.08.506363v1&sa=D&source=docs&ust=1673970408432251&usg=AOvVaw00cJiZ6UzZ_cqtGghBcumv) - data available on [https://open.win.ox.ac.uk/DigitalBrainBank/#/](https://www.google.com/url?q=https://open.win.ox.ac.uk/DigitalBrainBank/%23/&sa=D&source=docs&ust=1673970408432350&usg=AOvVaw1f4bNg3amlY71Di7lIgk1N)

**Comment by Diffusion-MRI** [comment]
Closed
